In [1]:
import numpy

In [2]:
import numpy as np

Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [6]:
arr= np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [22]:
l1=[]
n=int(input("enter the value:"))
for i in range(0,n):
    y=int(input())
    l1.append(y)
print(l1)

enter the value:5
4
3
2
1
5
[4, 3, 2, 1, 5]


In [23]:
l2=[]
n=int(input("enter the value:"))
for i in range(0,n):
    y=int(input())
    l2.append(y)
print(l2)

enter the value:5
8
7
9
6
4
[8, 7, 9, 6, 4]


In [24]:
l1

[4, 3, 2, 1, 5]

In [25]:
l2

[8, 7, 9, 6, 4]

In [26]:
arr1=np.array(l1)

In [27]:
arr2=np.array(l2)

In [30]:
print (arr1)

[4 3 2 1 5]


In [31]:
print (arr2)

[8 7 9 6 4]


In [32]:
type(arr1)

numpy.ndarray

In [33]:
type(arr2)

numpy.ndarray

In [51]:
np.concatenate([arr1,arr2])

array([4, 3, 2, 1, 5, 8, 7, 9, 6, 4])

In [57]:
print (np.sort(arr1))

[1 2 3 4 5]


In [58]:
print (np.sort(arr2))

[4 6 7 8 9]


In [59]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


In [63]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [64]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [65]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [70]:
a2=[1,6]
b=np.reshape(a2,(-1,2))
b

array([[1, 6]])

In [71]:
x = np.array([3, 5, 7])
y = np.array([5, 7, 9])
np.vstack((x,y))

array([[3, 5, 7],
       [5, 7, 9]])

In [73]:
x = np.array([3, 5, 7])
>>> y = np.array([5, 7, 9])
>>> np.hstack((x,y))

array([3, 5, 7, 5, 7, 9])

In [75]:
l= [1, 1, 2, 2, 3]
s= set(l)
u = len(s)
print(u)

3
